#!/bin/bash

R='\033[0;31m'
G='\033[0;32m'
Y='\033[0;33m'
B='\033[0;34m'
NC='\033[0m'

info=${Y}" [info]"${NC}
error=${R}"[error]"${NC}

CHECK=${G}'\xE2\x9C\x94'${NC}

script_path=$(readlink -f "$0")
scripts_dir=$(dirname "$script_path")

DB_FILE=$HOME"/.projects.db"
MAPRO_VERSION="version 0.01-alpha"

checkVersion() {
	if [[ -f $DB_FILE ]]; then
		MAPRO_DB_VERSION=$(sqlite3 "$DB_FILE" "SELECT version FROM config;")
		echo -e "\tDB:\t"$MAPRO_DB_VERSION
	fi
	
	echo -e "\tmapro:\t"$MAPRO_VERSION	
}

helpFunction() {
	echo -e ""
	echo -e "${Y}mapro${NC} is there to help you organize your projects."
	echo -e "Create a generic folder structure and files to document and"
	echo -e "keep track of your porjects."
	echo -e ""
	echo -e "usage:\t${Y}mapro${NC} <${G}function${NC}> -h"
	echo -e ""
	echo -e "Available helper scripts:"
	echo -e ""
	echo -e "\t${G}create${NC}\t  creates a new project with folder" \
			"structure"
	echo -e "\t\t  and files to keep track of things."
	echo -e "\t${G}check${NC}\t  overview of created projects to" \
			"keep track"
	echo -e "\t\t  of what you're doing"
	echo -e "\t${G}edit${NC}\t  editing an existing project"
	echo -e "\t\t  (e.g. rename, move, change project status)"
	echo -e "\t${G}remove${NC}\t  removes an existing project"
	echo -e "\t\t  (completely deletes everything)"
	echo -e "\t${G}activate${NC}  lets you edit contents in"
	echo -e "\t\t  the project folder."
	echo -e "\t${G}version${NC}\t  Print version and quit."
	echo -e ""
}

while true; do
    script_name=$1

    case $script_name in
	create )
		$scripts_dir"/scripts/create" "${@:2}"
		break
		;;
	check )
		$scripts_dir"/scripts/check" "${@:2}"
		break
		;;
	edit )
	    $scripts_dir"/scripts/edit" "${@:2}"
	    break
	    ;;
	remove )
	    $scripts_dir"/scripts/remove" "${@:2}"
	    break
	    ;;
	status )
	    $scripts_dir"/scripts/status" "${@:2}"
	    break
	    ;;
	activate )
	    $scripts_dir"/scripts/activate" "${@:2}"
	    break
	    ;;
	version )
	    checkVersion
	    exit 0
	    ;;
	-h | --help | help )
		helpFunction
		exit 0
		;;
	* )
		helpFunction
		exit 0
		;;
    esac
done
